In [0]:
import numpy.matlib 
import numpy as np 
import math 


In [0]:
#Problem 3
#Frame

r0 = np.array([100,200,300])
v0 = np.array([-50,30,-10])
a0 = ([ -15, 40 ,25])

angV = np.array([1, -.4, 0.6])
angA = np.array([-1, .3, -0.4])

#P

r = np.array([300,-100, 150])
v = np.array([70,25,-20])
a = np.array([7.5,8.5,6])

recef = r - r0
print(recef)

vecef = v - (v0 + np.cross(angV, recef))
print(vecef)

aecef = a - (a0 + np.cross(angA, recef) + np.cross(angV, np.cross(angV, recef))\
             + np.cross(2*angV,vecef))

print(aecef)


[ 200 -300 -150]
[-120. -275.  210.]
[ 99.5 398.5  21. ]


In [0]:
#Problem 4

phi = 35.7
lam = 139.7

#traveling NE at 7.01 km/s relative to ECEF frame

r_earth = 6378
w_earth = math.pi / (24*3600)

xdot = 4.96
ydot = 4.96

#altitude 
z = 1200 

change_phi = ydot/(r_earth + z)
print(change_lat)

change_lambda = xdot/((r_earth + z)*math.cos(math.radians(phi)))
print(change_long)

veci = np.array([xdot + w_earth*(r_earth+z)*math.cos(math.radians(phi)), ydot, 0])
veci





0.0006545262602269728
0.0008059839148962016


array([5.18376463, 4.96      , 0.        ])